name: ai_image_generator
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  bloc: ^9.0.0
  equatable: ^2.0.7
  internet_connection_checker_plus: ^2.7.0
  flutter_dotenv: ^5.2.1
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^3.0.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  